/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxy_web_service_constants.h"

namespace rpc {

const proxy_web_serviceConstants g_proxy_web_service_constants;

proxy_web_serviceConstants::proxy_web_serviceConstants() {
}

} // namespace

