/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proxy_web_service_CONSTANTS_H
#define proxy_web_service_CONSTANTS_H

#include "proxy_web_service_types.h"

namespace rpc {

class proxy_web_serviceConstants {
 public:
  proxy_web_serviceConstants();

};

extern const proxy_web_serviceConstants g_proxy_web_service_constants;

} // namespace

#endif
